### ISSUE TITLE
Docker-compose 报错 swoole http server process is already running.

### ISSUE THREAD

**Issue by anydson** [top-think/think-swoole#189]
docker-compose up
Starting tp_swoole ... done
Attaching to tp_swoole
tp_swoole | swoole http server process is already running.
tp_swoole exited with code 0

第一次运行正常, 重启后无效

docker run -it -v /home/project/tp:/var/www --network=network-c -p 900:9000 php74 php think swoole

`swoole http server process is already running.`

PID   USER     TIME  COMMAND
    1 root      0:00 ps

docker-compose.yml
```
version: '3.8'
services:
  php:
    image: php74
    container_name: tp_swoole
    networks:
      network-c:
        ipv4_address: 172.18.0.83
    ports:
      - 9000:9000
    tty: true
    volumes:
      - .:/var/www:rw
      - ./php.ini:/usr/local/etc/php/php.ini:rw
    command: 
      - php
      - think
      - swoole
networks:
  network-c:
    external: true
```

[图片不显示.........]

```
[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
67e226963365        redis:6.0           "docker-entrypoint.s…"   24 hours ago        Up 22 hours         0.0.0.0:6379->6379/tcp   redis
842f55ec1375        mariadb:10.4        "docker-entrypoint.s…"   2 weeks ago         Up 22 hours         0.0.0.0:3306->3306/tcp   mariadb
642ff825007a        nginx:1.19          "/docker-entrypoint.…"   2 weeks ago         Up 22 hours         0.0.0.0:7180->80/tcp     nginx
[root@localhost ~]# docker run -it -v /home/project/tp:/var/www --network=network-c -p 900:9000 php74 php think swoole
swoole http server process is already running.
[root@localhost ~]# 
```
